#!/usr/bin/env bash
#
# unit/mayhem/build.sh — build nginx/unit's five libFuzzer harnesses with sanitizers.
#
# The fuzzed surface includes:
#   fuzz_basic           — low-level utility functions (base64, hash, URI parsing, etc.)
#   fuzz_http_controller — HTTP controller message parsing
#   fuzz_http_h1p        — HTTP/1.1 protocol parsing
#   fuzz_http_h1p_peer   — HTTP/1.1 peer message parsing
#   fuzz_json            — JSON parsing
#
# Build contract comes from the org base ENV (CC/CXX/SANITIZER_FLAGS/LIB_FUZZING_ENGINE/SRC).
set -euo pipefail

# clang rejects SOURCE_DATE_EPOCH='' — must be unset or a valid integer.
[ -n "${SOURCE_DATE_EPOCH:-}" ] || unset SOURCE_DATE_EPOCH

# `=` (not `:=`) for SANITIZER_FLAGS so an explicit empty --build-arg builds with NO sanitizers.
: "${SANITIZER_FLAGS=-fsanitize=address,undefined -fno-sanitize-recover=all -fno-omit-frame-pointer -g}"
: "${DEBUG_FLAGS:=-g -gdwarf-3}"
: "${CC:=clang}" ; : "${CXX:=clang++}" ; : "${LIB_FUZZING_ENGINE:=-fsanitize=fuzzer}"
: "${MAYHEM_JOBS:=$(nproc)}"
export SANITIZER_FLAGS DEBUG_FLAGS CC CXX LIB_FUZZING_ENGINE MAYHEM_JOBS

cd "$SRC"

# Set compile flags with DEBUG_FLAGS for DWARF<4 compliance.
#
# -fsanitize=fuzzer-no-link: unit's own Makefile (auto/make, generated by ./configure) only
# threads $LIB_FUZZING_ENGINE (here, --fuzz=$LIB_FUZZING_ENGINE -> $NXT_FUZZ) onto the FINAL
# link line of each fuzz_* binary (see auto/fuzzing) — it never reaches the per-file compile
# rules that build build/lib/libnxt.a (the actual fuzzed library code). Compiling libnxt.a with
# only SANITIZER_FLAGS/DEBUG_FLAGS gives it ASan/UBSan instrumentation but NO SanitizerCoverage,
# so libFuzzer/Mayhem see edges=0 no matter how long the fuzzer runs. -fsanitize=fuzzer-no-link
# adds coverage instrumentation (SanitizerCoverage) at COMPILE time without pulling in a second
# libFuzzer main/driver, so it's safe to put on CFLAGS/CXXFLAGS (used for every .o, including
# libnxt.a's) alongside the real fuzzer runtime that gets linked into each fuzz_* binary via
# $NXT_FUZZ ($LIB_FUZZING_ENGINE) at link time.
CFLAGS="${SANITIZER_FLAGS} -fsanitize=fuzzer-no-link ${DEBUG_FLAGS}"
CXXFLAGS="${SANITIZER_FLAGS} -fsanitize=fuzzer-no-link ${DEBUG_FLAGS}"
export CFLAGS CXXFLAGS

# Unit uses autoconf; configure with fuzzing enabled
./configure --no-regex --no-pcre2 --fuzz="$LIB_FUZZING_ENGINE"

# Build the fuzzers with make fuzz
make fuzz -j"$MAYHEM_JOBS"

# Copy all fuzz targets to /mayhem
mkdir -p /mayhem
cp build/fuzz_basic /mayhem/
cp build/fuzz_http_controller /mayhem/
cp build/fuzz_http_h1p /mayhem/
cp build/fuzz_http_h1p_peer /mayhem/
cp build/fuzz_json /mayhem/

# ── Standalone KAT checker (nxt_checker) ─────────────────────────────────────────────────────
# mayhem/test.sh needs a REAL behavioral oracle (§6.3), not a libFuzzer-stats/exit-code proxy.
# nxt_checker.c is a plain (non-libFuzzer) program with its own main() that calls the SAME
# library entry points the fuzz targets exercise — nxt_base64_decode (fuzz_basic),
# nxt_conf_json_parse_str (fuzz_json), nxt_http_parse_request (fuzz_http_h1p / _controller /
# _h1p_peer all call this same request-line parser) — on FIXED input, and prints the computed
# result as "key=value" lines. Link it against the already-built build/lib/libnxt.a (same static
# lib the fuzz targets link) with the project's own runtime libs (-lm -lrt -lpthread, per
# auto/os/conf's Linux branch) — no libFuzzer engine, since nxt_checker.c supplies its own main().
"$CC" -c $CFLAGS -std=gnu11 -I src -I build/include \
    -o build/fuzzing/nxt_checker.o mayhem/nxt_checker.c
"$CC" -Wl,-E $CFLAGS -o /mayhem/nxt_checker \
    build/fuzzing/nxt_checker.o build/lib/libnxt.a -lm -lrt -lpthread

echo "build.sh complete:"
ls -la /mayhem/fuzz_* /mayhem/nxt_checker 2>&1 || true

# mayhem-dict-fix: place the dictionaries the Mayhemfiles reference (build.sh never did -> libFuzzer exited 1 on missing -dict -> 0 edges)
find "$SRC/mayhem" -name "*.dict" -exec cp {} /mayhem/ \; 2>/dev/null || true
